//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc3.Areas.AdminPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class favorim
    {
        public int id { get; set; }
        public Nullable<int> productId { get; set; }
        public Nullable<int> userId { get; set; }
    
        public virtual urun urun { get; set; }
        public virtual user user { get; set; }
    }
}
