//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc3.Areas.AdminPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class indirim
    {
        public int indirimNo { get; set; }
        public string indirimKodu { get; set; }
        public string aciklama { get; set; }
        public Nullable<decimal> indirimTutar { get; set; }
        public Nullable<System.DateTime> indirimBaslangic { get; set; }
        public Nullable<System.DateTime> indirimBitis { get; set; }
        public Nullable<int> musteriNo { get; set; }
        public Nullable<bool> indirimDurum { get; set; }
        public Nullable<bool> kullanidiMi { get; set; }
        public virtual user user { get; set; }
    }
}
