//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvc3.Areas.AdminPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class yorum
    {
        public int yorumNo { get; set; }
        public Nullable<int> urunNo { get; set; }
        public string yorumAdi { get; set; }
        public string yorumcu { get; set; }
        public Nullable<System.DateTime> yorumTarihi { get; set; }
    
        public virtual urun urun { get; set; }
    }
}
